#!/bin/bash
#usage: ./PrintInfo.sh [<SourceDir> [<BuildDir>]]
#echo PrintInfo.sh $1 $2
#echo current dir: $PWD
buildDir=`pwd`
if [ $# -gt 0 ]
then
    cd $1
    if [ $# -gt 1 ]
    then
	buildDir=$2
    fi
fi
## search for ResourceCompile file
if [ -f ${buildDir}/ResourceCompile ]
then
    ResourceCompile="${buildDir}/ResourceCompile"
elif [ -f ${buildDir}/Debug/ResourceCompile ]
then
    ResourceCompile="${buildDir}/Debug/ResourceCompile"
elif [ -f ${buildDir}/Release/ResourceCompile ]
then
    ResourceCompile="${buildDir}/Release/ResourceCompile"
fi
date +"  built on %A %B %d %Y %t%T\"" > ${buildDir}/__buildTime
echo -n "#define RELEASE_INFO \"rev. " > ${buildDir}/__start
if git status . 1>/dev/null 2>&1 #if version control is available
    then
    ./PrintVersionInfo.sh > ${buildDir}/__versionInfo
    $ResourceCompile EncodedVersion ${buildDir}/__versionInfo > ${buildDir}/_autogeneratedGitInfo.c
    cat ${buildDir}/__start ${buildDir}/__versionInfo ${buildDir}/__buildTime > ${buildDir}/_autogeneratedVersionInfo.h
    rm ${buildDir}/__buildTime ${buildDir}/__start ${buildDir}/__versionInfo
    echo "bla bla" > ${buildDir}/VersionInfo.o
    rm ${buildDir}/VersionInfo.o
    git diff > ${buildDir}/_git.diff
    $ResourceCompile EncodedDif ${buildDir}/_git.diff > ${buildDir}/_autogeneratedDif.c
    rm ${buildDir}/_git.diff
else #don't use git, generate stub
    echo -n "0" > __versionInfo
    $ResourceCompile EncodedVersion ${buildDir}/__versionInfo >${buildDir}/_autogeneratedGitInfo.c
    cat ${buildDir}/__start ${buildDir}/__versionInfo ${buildDir}/__buildTime >${buildDir}/_autogeneratedVersionInfo.h
    rm ${buildDir}/__buildTime ${buildDir}/__start ${buildDir}/__versionInfo
    echo "bla bla" > VersionInfo.o
    rm VersionInfo.o
    echo "StringResource EncodedDif;" > ${buildDir}/_autogeneratedDif.c
fi
